name: Build release

on: 
  push:
    branches:
      - main


jobs:

  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  build:
    runs-on: windows-latest
    needs: tag
    permissions:
      contents: write 
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    # Build, test & publish
    - name: Create github release
      run: .\build.ps1 Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
